### ISSUE TITLE
not able to install logsetup 

### ISSUE THREAD

**Issue by thrylos2307** [cartertemm/logsetup#2]
i am trying to install logsetup using : 
`pip install logsetup`

and getting the following error:
```
Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-isfk88g0/logsetup/setup.py", line 4, in <module>
        with open("readme.md", "r", encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'


```

**Comment by cartertemm** [comment]
Just resolved this in the latest version. You may have to uninstall, then `pip install logsetup==1.1`.

Thanks for the issue
